---
- name: Install python3, python3-pip, python-is-python3
  become: true
  apt:
    pkg:
      - python3
      - python3-pip
      - python-is-python3
    update_cache: true

- name: Add node.js LTS source
  shell: curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

- name: Install node.js, npm
  become: true
  apt:
    pkg:
      - nodejs
      - npm
    update_cache: true

- name: Install yarn
  shell: npm install -g yarn

- name: Install rust
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

- name: Install cargo
  become: true
  apt:
    pkg:
      - cargo
    update_cache: true
