---
- name: Update repositories
  become: true
  apt: update_cache=true
  changed_when: false

- name: Install python3, python3-pip, python-is-python3
  become: true
  apt:
    pkg:
      - python3
      - python3-pip
      - python-is-python3

- name: Add node.js LTS source
  become: true
  shell: bash -c "$(curl -fsSL https://deb.nodesource.com/setup_lts.x)"

- name: Install Node.js LTS (include npm and yarn)
  become: true
  apt:
    pkg:
      - nodejs
    update_cache: true

- name: Check if cargo is installed
  shell: command -v cargo >/dev/null 2>&1
  register: cargo_exists
  ignore_errors: true

- name: Install rustc, cargo
  when: cargo_exists is failed
  shell: sh -c "$(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs)"
