---
- name: Install python3, python3-pip, python-is-python3
  become: true
  apt:
    pkg:
      - python3
      - python3-pip
      - python-is-python3
    update_cache: true
    cache_valid_time: 3600

- name: Install nodejs, npm
  become: true
  apt:
    pkg:
      - nodejs
      - npm
    update_cache: true
    cache_valid_time: 3600

- name: Install yarn
  shell: npm install -g yarn

- name: Install rustc, cargo
  become: true
  apt:
    pkg:
      - rustc
      - cargo
    update_cache: true
    cache_valid_time: 3600
